### ISSUE TITLE
ESP8266 FOTA example

### ISSUE THREAD

**Issue by fvpalha** [martincalsyn/Molarity#1]
Hi Martin.

I am sorry, but this was the unique mode to ask you.

Do you have a FOTA example with [Unofficial Development Kit for Espressif ESP8266](https://github.com/CHERTS/esp8266-devkit) ?

I want to add this feature in my project.

Best regards.

[Snippet - Generic ESP8266 and network support libraries](https://www.ghielectronics.com/community/forum/topic?id=19036&page=2#msg193873)

**Comment by martincalsyn** [comment]
Ooops!  Just saw this as I was getting ready to get rid of this repo (it never went anywhere).  No, I don't have such an example, sorry.
